# -*- mode: python ; coding: utf-8 -*-
specpath = os.path.dirname(os.path.abspath(SPEC))

block_cipher = None


a = Analysis(['main.py'],
             pathex=['ENTER PATH TO main.py HERE'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
for d in a.datas:
    if 'pyconfig' in d[0]:
        a.datas.remove(d)
        break

a.datas += [('StartWindowBackground.png',specpath + '\\GUIPictures\\StartWindowBackground.png', 'Data'),
('StartButtonBackground.png',specpath + '\\GUIPictures\\StartButtonBackground.png', 'Data'),
('CloseButtonBackground.png',specpath + '\\GUIPictures\\CloseButtonBackground.png', 'Data'),
('ComboBoxBackground.png',specpath + '\\GUIPictures\\ComboBoxBackground.png', 'Data'),
('InfoButton.png',specpath + '\\GUIPictures\\InfoButton.png', 'Data'),
('OverlayBackground.png',specpath + '\\GUIPictures\\OverlayBackground.png', 'Data'),
('SettingsButton.png',specpath + '\\GUIPictures\\SettingsButton.png', 'Data'),
('RefreshButton.png',specpath + '\\GUIPictures\\RefreshButton.png', 'Data'),
('OkButton.png',specpath + '\\GUIPictures\\OkButton.png', 'Data'),
('DonateWindowBackground.png',specpath + '\\GUIPictures\\DonateWindowBackground.png', 'Data'),
('PayPalButton.png',specpath + '\\GUIPictures\\PayPalButton.png', 'Data'),
('GitHubButton.png',specpath + '\\GUIPictures\\GitHubButton.png', 'Data'),
('CCIcon.png',specpath + '\\GUIPictures\\CCIcon.png', 'Data'),           
('Empty.png',specpath + '\\CurrencyIcons\\Empty.png', 'Data'),
('OrbofAlteration.png',specpath + '\\CurrencyIcons\\OrbofAlteration.png', 'Data'),
('OrbofFusing.png',specpath + '\\CurrencyIcons\\OrbofFusing.png', 'Data'),
('OrbofAlchemy.png',specpath + '\\CurrencyIcons\\OrbofAlchemy.png', 'Data'),
('ChaosOrb.png',specpath + '\\CurrencyIcons\\ChaosOrb.png', 'Data'),
('ChromaticOrb.png',specpath + '\\CurrencyIcons\\ChromaticOrb.png', 'Data'),
('JewellersOrb.png',specpath + '\\CurrencyIcons\\JewellersOrb.png', 'Data'),
('OrbofChance.png',specpath + '\\CurrencyIcons\\OrbofChance.png', 'Data'),
('CartographersChisel.png',specpath + '\\CurrencyIcons\\CartographersChisel.png', 'Data'),
('OrbofScouring.png',specpath + '\\CurrencyIcons\\OrbofScouring.png', 'Data'),
('BlessedOrb.png',specpath + '\\CurrencyIcons\\BlessedOrb.png', 'Data'),
('RegalOrb.png',specpath + '\\CurrencyIcons\\RegalOrb.png', 'Data'),
('VaalOrb.png',specpath + '\\CurrencyIcons\\VaalOrb.png', 'Data'),
('SacrificeatDusk.png',specpath + '\\CurrencyIcons\\SacrificeatDusk.png', 'Data'),
('SacrificeatMidnight.png',specpath + '\\CurrencyIcons\\SacrificeatMidnight.png', 'Data'),
('SacrificeatDawn.png',specpath + '\\CurrencyIcons\\SacrificeatDawn.png', 'Data'),
('SacrificeatNoon.png',specpath + '\\CurrencyIcons\\SacrificeatNoon.png', 'Data'),
('MortalGrief.png',specpath + '\\CurrencyIcons\\MortalGrief.png', 'Data'),
('MortalRage.png',specpath + '\\CurrencyIcons\\MortalRage.png', 'Data'),
('MortalHope.png',specpath + '\\CurrencyIcons\\MortalHope.png', 'Data'),
('MortalIgnorance.png',specpath + '\\CurrencyIcons\\MortalIgnorance.png', 'Data'),
('OfferingtotheGoddess.png',specpath + '\\CurrencyIcons\\OfferingtotheGoddess.png', 'Data'),
('SimpleSextant.png',specpath + '\\CurrencyIcons\\SimpleSextant.png', 'Data'),
('PrimeSextant.png',specpath + '\\CurrencyIcons\\PrimeSextant.png', 'Data'),
('AwakenedSextant.png',specpath + '\\CurrencyIcons\\AwakenedSextant.png', 'Data'),
('OrbofHorizons.png',specpath + '\\CurrencyIcons\\OrbofHorizons.png', 'Data'),
('SilverCoin.png',specpath + '\\CurrencyIcons\\SilverCoin.png', 'Data'),     
('refEmpty.png',specpath + '\\CurrencyReferences\\Empty.png', 'Data'),
('refOrbofAlteration.png',specpath + '\\CurrencyReferences\\OrbofAlteration.png', 'Data'),
('refOrbofFusing.png',specpath + '\\CurrencyReferences\\OrbofFusing.png', 'Data'),
('refOrbofAlchemy.png',specpath + '\\CurrencyReferences\\OrbofAlchemy.png', 'Data'),
('refChaosOrb.png',specpath + '\\CurrencyReferences\\ChaosOrb.png', 'Data'),
('refChromaticOrb.png',specpath + '\\CurrencyReferences\\ChromaticOrb.png', 'Data'),
('refJewellersOrb.png',specpath + '\\CurrencyReferences\\JewellersOrb.png', 'Data'),
('refOrbofChance.png',specpath + '\\CurrencyReferences\\OrbofChance.png', 'Data'),
('refCartographersChisel.png',specpath + '\\CurrencyReferences\\CartographersChisel.png', 'Data'),
('refOrbofScouring.png',specpath + '\\CurrencyReferences\\OrbofScouring.png', 'Data'),
('refBlessedOrb.png',specpath + '\\CurrencyReferences\\BlessedOrb.png', 'Data'),
('refRegalOrb.png',specpath + '\\CurrencyReferences\\RegalOrb.png', 'Data'),
('refVaalOrb.png',specpath + '\\CurrencyReferences\\VaalOrb.png', 'Data'),
('refSacrificeatDusk.png',specpath + '\\CurrencyReferences\\SacrificeatDusk.png', 'Data'),
('refSacrificeatMidnight.png',specpath + '\\CurrencyReferences\\SacrificeatMidnight.png', 'Data'),
('refSacrificeatDawn.png',specpath + '\\CurrencyReferences\\SacrificeatDawn.png', 'Data'),
('refSacrificeatNoon.png',specpath + '\\CurrencyReferences\\SacrificeatNoon.png', 'Data'),
('refMortalGrief.png',specpath + '\\CurrencyReferences\\MortalGrief.png', 'Data'),
('refMortalRage.png',specpath + '\\CurrencyReferences\\MortalRage.png', 'Data'),
('refMortalHope.png',specpath + '\\CurrencyReferences\\MortalHope.png', 'Data'),
('refMortalIgnorance.png',specpath + '\\CurrencyReferences\\MortalIgnorance.png', 'Data'),
('refOfferingtotheGoddess.png',specpath + '\\CurrencyReferences\\OfferingtotheGoddess.png', 'Data'),
('refSimpleSextant.png',specpath + '\\CurrencyReferences\\SimpleSextant.png', 'Data'),
('refPrimeSextant.png',specpath + '\\CurrencyReferences\\PrimeSextant.png', 'Data'),
('refAwakenedSextant.png',specpath + '\\CurrencyReferences\\AwakenedSextant.png', 'Data'),
('refOrbofHorizons.png',specpath + '\\CurrencyReferences\\OrbofHorizons.png', 'Data'),
('refSilverCoin.png',specpath + '\\CurrencyReferences\\SilverCoin.png', 'Data')]


pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='ChaosCounter',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False)
