# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['ENTER PATH TO main.py HERE'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
for d in a.datas:
    if 'pyconfig' in d[0]:
        a.datas.remove(d)
        break

a.datas += [('StartWindowBackground.png','\GUIPictures\StartWindowBackground.png', 'Data'),
('StartButtonBackground.png','\GUIPictures\StartButtonBackground.png', 'Data'),
('CloseButtonBackground.png','\GUIPictures\CloseButtonBackground.png', 'Data'),
('ComboBoxBackground.png','\GUIPictures\ComboBoxBackground.png', 'Data'),
('InfoButton.png','\GUIPictures\InfoButton.png', 'Data'),
('OverlayBackground.png','\GUIPictures\OverlayBackground.png', 'Data'),
('SettingsButton.png','\GUIPictures\SettingsButton.png', 'Data'),
('RefreshButton.png','\GUIPictures\RefreshButton.png', 'Data'),
('OkButton.png','\GUIPictures\OkButton.png', 'Data'),
('DonateWindowBackground.png','\GUIPictures\DonateWindowBackground.png', 'Data'),
('PayPalButton.png','\GUIPictures\PayPalButton.png', 'Data'),
('GitHubButton.png','\GUIPictures\GitHubButton.png', 'Data'),
('CCIcon.png','\GUIPictures\CCIcon.png', 'Data'),           
('Empty.png','\CurrencyIcons\Empty.png', 'Data'),
('OrbofAlteration.png','\CurrencyIcons\OrbofAlteration.png', 'Data'),
('OrbofFusing.png','\CurrencyIcons\OrbofFusing.png', 'Data'),
('OrbofAlchemy.png','\CurrencyIcons\OrbofAlchemy.png', 'Data'),
('ChaosOrb.png','\CurrencyIcons\ChaosOrb.png', 'Data'),
('ChromaticOrb.png','\CurrencyIcons\ChromaticOrb.png', 'Data'),
('JewellersOrb.png','\CurrencyIcons\JewellersOrb.png', 'Data'),
('OrbofChance.png','\CurrencyIcons\OrbofChance.png', 'Data'),
('CartographersChisel.png','\CurrencyIcons\CartographersChisel.png', 'Data'),
('OrbofScouring.png','\CurrencyIcons\OrbofScouring.png', 'Data'),
('BlessedOrb.png','\CurrencyIcons\BlessedOrb.png', 'Data'),
('RegalOrb.png','\CurrencyIcons\RegalOrb.png', 'Data'),
('VaalOrb.png','\CurrencyIcons\VaalOrb.png', 'Data'),
('SacrificeatDusk.png','\CurrencyIcons\SacrificeatDusk.png', 'Data'),
('SacrificeatMidnight.png','\CurrencyIcons\SacrificeatMidnight.png', 'Data'),
('SacrificeatDawn.png','\CurrencyIcons\SacrificeatDawn.png', 'Data'),
('SacrificeatNoon.png','\CurrencyIcons\SacrificeatNoon.png', 'Data'),
('MortalGrief.png','\CurrencyIcons\MortalGrief.png', 'Data'),
('MortalRage.png','\CurrencyIcons\MortalRage.png', 'Data'),
('MortalHope.png','\CurrencyIcons\MortalHope.png', 'Data'),
('MortalIgnorance.png','\CurrencyIcons\MortalIgnorance.png', 'Data'),
('OfferingtotheGoddess.png','\CurrencyIcons\OfferingtotheGoddess.png', 'Data'),
('SimpleSextant.png','\CurrencyIcons\SimpleSextant.png', 'Data'),
('PrimeSextant.png','\CurrencyIcons\PrimeSextant.png', 'Data'),
('AwakenedSextant.png','\CurrencyIcons\AwakenedSextant.png', 'Data'),
('OrbofHorizons.png','\CurrencyIcons\OrbofHorizons.png', 'Data'),
('SilverCoin.png','\CurrencyIcons\SilverCoin.png', 'Data'),     
('refEmpty.png','\CurrencyReferences\Empty.png', 'Data'),
('refOrbofAlteration.png','\CurrencyReferences\OrbofAlteration.png', 'Data'),
('refOrbofFusing.png','\CurrencyReferences\OrbofFusing.png', 'Data'),
('refOrbofAlchemy.png','\CurrencyReferences\OrbofAlchemy.png', 'Data'),
('refChaosOrb.png','\CurrencyReferences\ChaosOrb.png', 'Data'),
('refChromaticOrb.png','\CurrencyReferences\ChromaticOrb.png', 'Data'),
('refJewellersOrb.png','\CurrencyReferences\JewellersOrb.png', 'Data'),
('refOrbofChance.png','\CurrencyReferences\OrbofChance.png', 'Data'),
('refCartographersChisel.png','\CurrencyReferences\CartographersChisel.png', 'Data'),
('refOrbofScouring.png','\CurrencyReferences\OrbofScouring.png', 'Data'),
('refBlessedOrb.png','\CurrencyReferences\BlessedOrb.png', 'Data'),
('refRegalOrb.png','\CurrencyReferences\RegalOrb.png', 'Data'),
('refVaalOrb.png','\CurrencyReferences\VaalOrb.png', 'Data'),
('refSacrificeatDusk.png','\CurrencyReferences\SacrificeatDusk.png', 'Data'),
('refSacrificeatMidnight.png','\CurrencyReferences\SacrificeatMidnight.png', 'Data'),
('refSacrificeatDawn.png','\CurrencyReferences\SacrificeatDawn.png', 'Data'),
('refSacrificeatNoon.png','\CurrencyReferences\SacrificeatNoon.png', 'Data'),
('refMortalGrief.png','\CurrencyReferences\MortalGrief.png', 'Data'),
('refMortalRage.png','\CurrencyReferences\MortalRage.png', 'Data'),
('refMortalHope.png','\CurrencyReferences\MortalHope.png', 'Data'),
('refMortalIgnorance.png','\CurrencyReferences\MortalIgnorance.png', 'Data'),
('refOfferingtotheGoddess.png','\CurrencyReferences\OfferingtotheGoddess.png', 'Data'),
('refSimpleSextant.png','\CurrencyReferences\SimpleSextant.png', 'Data'),
('refPrimeSextant.png','\CurrencyReferences\PrimeSextant.png', 'Data'),
('refAwakenedSextant.png','\CurrencyReferences\AwakenedSextant.png', 'Data'),
('refOrbofHorizons.png','\CurrencyReferences\OrbofHorizons.png', 'Data'),
('refSilverCoin.png','\CurrencyReferences\SilverCoin.png', 'Data')]


pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='1080ptest',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False)
